---
title: "Chapter 3"
output: html_notebook
---
Chapter 3
```{r}
library(xts)
library(lubridate)
library(quantmod)
library(tidyverse)
library(reshape2)
library(tibbletime)
library(timetk)
library(highcharter)
library(formattable)

YEARS_BACK <- 5
symbols <-
  c("OLTYX",
    "OEGYX",
    "RDIV",
    "RMUYX",
    "ESGF",
    "OMFL",
    "OIMYX",
    "OIGYX",
    "GLVYX",
    "MIGYX")

source("../helper_functions.r")

```

```{r}

load("../data/raw_prices.rdata")
```

```{r}
prices<-timetk::tk_tbl(raw_prices) %>%
  rename(date=index) %>% 
  tibbletime::as_tbl_time(index=date) 

#monthlyize
prices <- prices %>% tibbletime::as_period("monthly",side="end")

#tidyfy it
prices <- prices %>% gather(symbol,price,-date) %>% group_by(symbol)

#one symbol has bad data for six months.  It looks like the NAV is doubled. Fix.
prices <- prices %>% mutate(price=ifelse((symbol=="OLTYX" & price > 6),price/2,price))

#create return series
returns <- prices %>% transmute(date=date,return=log(price)/lag(log(price))-1) %>% slice(-1)
returns
```


```{r eval=FALSE, include=FALSE}
#Make portfolio  Load positions
# not part of git
if (!file.exists("../data/portfolio.rdata")){
  positions<-read_csv("../data/Positions.csv")
  
  #filter out cash
  positions <- positions %>% filter(`Asset Strategy Detail` != "Cash")
  #convert to percentages
  portfolio<-positions %>% mutate(weight=Value/sum(Value)) %>%
    select(starts_with("Asset"),Description,Ticker,weight) %>% 
    rename(symbol=Ticker) %>% 
    mutate(name=gsub("OPPENHEIMER ","",Description)) %>% 
    #strip share class from end
    mutate(name=gsub("((-| )[A-Z])$","",name))
  
  save(portfolio,file="../data/portfolio.rdata")
}
```

```{r}
# this file is in repo.  Dollars are omitted for privacy.  Only weights.
load("../data/portfolio.rdata")
portfolio
```
```{r}
ggplot(portfolio,aes(symbol,weight,fill=`Asset Class`)) + geom_col()+ 
  scale_y_continuous(labels = scales::percent) +
  scale_fill_tq()
```
OR
```{r}
ggplot(portfolio,aes(`Asset Class`,weight,fill=name)) + geom_col() +
    scale_y_continuous(labels = scales::percent) +
  scale_fill_tq()

```

```{r}

portfolio_return<-returns %>%
  subset_year(2012) %>% 
  left_join(select(portfolio,symbol,weight)) %>% 
  group_by(date) %>% 
  summarise(return=sum(return*weight)) %>% 
  mutate(name="Portfolio") %>% 
  group_by(name)

# monkey with portfolio return so it conforms to the ggplot object
# returned by chart_cum_returns
w_port <- portfolio_return %>% ungroup() %>% 
  transmute(date=date,name=name,wealth=cumprod(1+return))
  
gg<-returns %>% left_join(portfolio) %>% group_by(name) %>%   
  subset_year(2012) %>% 
  chart_cum_returns(name_col = "name")

# add a heavy line for the blended portfolio
gg<-gg+geom_line(data=w_port,size=2)
gg

```

```{r}
ggplot(returns, aes(x=return,fill=symbol,color=symbol)) + 
  geom_density(alpha=0.2) +
  geom_density(data=rename(portfolio_return,symbol=name))

```

Volatility
```{r}
returns %>% subset_year(2012) %>% 
  group_by(symbol) %>% 
  summarise(vol_pct=volatility(return))
```

```{r}
volatility(portfolio_return$return,n=12)
```

Correlation Matrix
```{r}

returns %>% subset_year(2012) %>% 
  spread(symbol,return) %>% 
  select(-date) %>% 
  cov()  %>% 
  cov2cor() %>% 
  round(digits = 2) %>% 
  melt() %>% 
  ggplot(aes(Var1,Var2,fill=value))+geom_tile() +
  scale_fill_viridis_c()
```

